sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "12"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm i

script:
  - ng test --sourceMap=false --browsers ChromeHeadless --watch=false
